categories/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from django.urls import path, include 
from rest_framework import routers 
from categories import endpoints

from categories import admin
from categories import models 
from . import views 
from django.views.generic import TemplateView
from django.views.generic.detail import DetailView
from rest_framework.authtoken import views as authtoken_views


router = routers.DefaultRouter() 
router.register(r'orderlines', endpoints.PaidOrderLineViewSet) 
router.register(r'orders', endpoints.PaidOrderViewSet)

urlpatterns = [
    path(
        "contact-us/",
        views.ContactUsView.as_view(),
        name="contact_us",
    ),
   path(
        'signup/', 
        views.SignupView.as_view(), name="signup"),

    path('api/', include(router.urls)),
    #path( "customer-service/<int:order_id>/", views.room, name="cs_chats",),
    #path( "customer-service/", TemplateView.as_view(
            #template_name="customer_service.html" ), name="cs_categories", ),

    path(
        "address/", views.AddressListView.as_view(), name="address_list",
    ), 
    path(
        "address/create/", views.AddressCreateView.as_view(), name="address_create",
    ), 
    path(
        "address/<int:pk>/", views.AddressUpdateView.as_view(), name="address_update",
    ), 
    path(
        "address/<int:pk>/delete/", views.AddressDeleteView.as_view(), name="address_delete",
),
    path('my-order/', views.my_order_view,name='my-order'),
    path(
         "order-dashboard/", views.OrderView.as_view(), name="order_dashboard",
),

    path(
        "order/done/",
        TemplateView.as_view(template_name="order_done.html"),
        name="checkout_done",
    ),
    path(
        "order/address_select/",
        views.AddressSelectionView.as_view(),
        name="address_select",
    ),
    path(
        "add_to_basket/", views.add_to_basket, name="add_to_basket" ),

    path('basket/', views.manage_basket, name="basket"),

    path('search/', views.products, name="search_products"),

    path('product/', views.ProductListView.as_view(), name='product_list'),
    path('product/category/<slug:category>/', TemplateView.as_view(), name='category_show'),
    path('brands/<slug:slug>/', views.brand, name='brand'),

    path('brands/apple/', views.brand_apple, name='brand_apple'),
    path('brands/hp/', views.brand_hp, name='brand_hp'),
    path('brands/dell/', views.brand_dell, name='brand_dell'),
    path('brands/asus/', views.brand_asus, name='brand_asus'),
    path('brands/samsung/', views.brand_samsung, name='brand_samsung'),
    path('brands/lenovo/', views.brand_lenovo, name='brand_lenovo'),
    path('brands/toshiba/', views.brand_toshiba, name='brand_toshiba'),


    path('brands/programminglaptops/', views.brand_programminglaptops, name='brand_programminglaptops'),

    path('brands/businesslaptops/', views.brand_businesslaptops, name='brand_businesslaptops'),

    #path('room/<int:id>/<slug:slug>/', views.product_chat_room, name='product_chat_room'),
#path( "customer-service/<int:order_id>/", views.room, name="cs_chats",),

    path('category/<slug:category>/', views.ProductListView.as_view(), name='product_list_category'),
    path('bestseller/', views.product_bestseller, name='product_bestseller'),
    #path('flashsales/', views.product_flashsales, name='product_flashsales'),
    path('bestdeals/', views.product_bestdeals, name='product_bestdeals'),
    #path('featured/', views.product_featured, name='product_featured'),
    #path('toppicksforyou/', views.product_toppicksforyou, name='product_toppicksforyou'),
    

    #path('<uuid:pk>/', views.ProductDetailView.as_view(), name='product_detail'),
    
    path('<int:id>/<slug:slug>/', views.product_detail,name='product_detail'),
    path(
        "mobile-api/auth/", 
        authtoken_views.obtain_auth_token, 
        name="mobile_token",
),

    path( "mobile-api/my-orders/", 
    endpoints.my_orders, 
    name="mobile_my_orders",
),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)


#33pastebin

mackenya/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from categories import views
from categories.views import ProductListView
from django.views.generic import TemplateView
from django.contrib.auth import views as auth_views
from categories import forms
from categories import admin

urlpatterns = [
    path('admin/', admin.categories_admin.urls),
    path("office-admin/", admin.central_office_admin.urls),
    path("dispatch-admin/", admin.dispatchers_admin.urls),
    
    path(
        "order-dashboard/", views.OrderView.as_view(), name="order_dashboard",
),
    path(
        "contact-us/",
        views.ContactUsView.as_view(),
        name="contact_us",
    ),

    path(
        'signup/', 
        views.SignupView.as_view(), name="signup"),
   path(
        "login/", auth_views.LoginView.as_view( template_name="login.html",
        form_class=forms.AuthenticationForm, ),
        name="login",
), 
  path('logout/', auth_views.LogoutView.as_view(), name='logout'),

    path('api-auth/', include('rest_framework.urls')),
    #path('cart/', include('cart.urls', namespace='cart')),
    #path('orders/', include('orders.urls', namespace='orders')),
    #path('payment/', include('payment.urls', namespace='payment')),
    path('product/', include('categories.urls', )),
    #path('marketing/', include('carousel.urls', namespace='carousel')),
    ##path('search', include('search.urls', namespace='search')),
    #path('', ProductListView.as_view(), name='product_list'),
    path('', views.index, name='index'),
    #path('', views.home, name='home'),
    #path('', TemplateView.as_view(template_name="other/carousel.html")),

    re_path(r'^ckeditor/', include('ckeditor_uploader.urls')),
  

   
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

#handler404 = 'mackenya.views.file_not_found_404'

categories/models.py
import uuid
from django.urls import reverse
import django_filters
from django.db import models
from django.contrib.contenttypes.models import ContentType
from django.contrib.contenttypes.fields import GenericForeignKey
from .fields import OrderField
from django.utils.text import slugify
from django.template.loader import render_to_string

from django.core.validators import MinValueValidator
from django.db.models import Count, Sum



from ckeditor_uploader.fields import RichTextUploadingField 

from django.conf import settings
#from . import exceptions

import logging
logger = logging.getLogger(__name__)

from django.contrib.auth.models import ( 
    AbstractUser,
    BaseUserManager,
)

class UserManager(BaseUserManager): 
    use_in_migrations = True
    
    def _create_user(self, email, password,**extra_fields): 
        if not email:
            raise ValueError("The given email must be set") 
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password) 
        user.save(using=self._db) 
        return user

    def create_user(self, email, password=None, **extra_fields): 
        extra_fields.setdefault("is_staff", False) 
        extra_fields.setdefault("is_superuser", False)
        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email, password, **extra_fields): 
        extra_fields.setdefault("is_staff", True) 
        extra_fields.setdefault("is_superuser", True)

        if extra_fields.get("is_staff") is not True: 
            raise ValueError(
                "Superuser must have is_staff=True." )
        if extra_fields.get("is_superuser") is not True: 
            raise ValueError(
                "Superuser must have is_superuser=True." )
        return self._create_user(email, password, **extra_fields)

class User(AbstractUser): 
    username = None
    email = models.EmailField('email address', unique=True)

    USERNAME_FIELD = 'email' 
    REQUIRED_FIELDS = []
    
    objects = UserManager()

    @property
    def is_employee(self):
        return self.is_active and (
            self.is_superuser
            or self.is_staff
            and self.groups.filter(name="Employees").exists()
        )

    @property
    def is_dispatcher(self):
        return self.is_active and (
            self.is_superuser
            or self.is_staff
            and self.groups.filter(name="Dispatchers").exists()
        )

from django.template.loader import render_to_string
# Create your models here.
class ActiveManager(models.Manager): 
    def active(self):
        return self.filter(active=True)

class Brand(models.Model):
    title = models.CharField(max_length=255, default='') 
    slug = models.SlugField(max_length=200, unique=True, help_text='Type the brand of your product in small letters')
    class Meta:
        ordering = ['title']


    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('brand', args=[self.slug])



class Category(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200, unique=True, help_text='Type the title of your product in small letters') 
    meta_keywords = models.CharField("Meta Keywords",max_length=255, help_text='Comma-delimited set of SEO keywords for meta tag') 
    meta_description = models.CharField("Meta Description", max_length=255,help_text='Content for description meta tag') 
    class Meta:
        ordering = ['title'] 
        verbose_name = 'category'
        verbose_name_plural = 'categories'
    
    def __str__(self):
        return self.title 


    objects = ActiveManager()

class ActiveProductManager(models.Manager): 
    def get_query_set(self):
        return super(ActiveProductManager, self).get_query_set().filter(is_active=True)


class FeaturedProductManager(models.Manager): 
    def all(self):
        return super(FeaturedProductManager, self).all() .filter(is_active=True).filter(featured=True)

class Product(models.Model):
    #id = models.UUIDField(
        #primary_key=True, default=uuid.uuid4, editable=False)
    brands = models.ManyToManyField(Brand, blank=True)

    category = models.ForeignKey(Category, related_name='products',on_delete=models.CASCADE) 

    #release_date = models.DateField()
    title = models.CharField(max_length=200, help_text='Title of your product, e.g Sofa')
    #image = models.ImageField(upload_to='products/%Y/%m/%d',blank=True)
    #image2 = models.ImageField(upload_to='products/%Y/%m/%d',blank=True)
    #image3 = models.ImageField(upload_to='products/%Y/%m/%d',blank=True)

    is_active = models.BooleanField(default=True) 
    bestseller = models.BooleanField(default=False, help_text="1=bestseller") 
    flashsales = models.BooleanField(default=False, help_text="1=flashsales") 
    toppicksforyou = models.BooleanField(default=False, help_text="1=Top picks for you") 
    monthlysales= models.BooleanField(default=False, help_text="1=monthlysales") 
    bestdeals= models.BooleanField(default=False, help_text="1=bestdeals") 
    brand = models.CharField(max_length=50)
    sku = models.CharField(max_length=50)
    price = models.DecimalField(max_digits=9,decimal_places=2,help_text='Current price')
    old_price = models.DecimalField(max_digits=9,decimal_places=2,blank=True,default=0.00, help_text='Old price')
    quantity = models.IntegerField()
    slug = models.SlugField(max_length=200, unique=True, help_text='Type the title of your product in small letters, e.g sofa') 
    meta_keywords = models.CharField(max_length=255,help_text='Comma-delimited set of SEO keywords for meta tag') 
    meta_description = models.CharField(max_length=255,help_text='Content for description meta tag') 
    #overview = models.TextField(help_text='Describe your product and terms')
    overview = RichTextUploadingField() # CKEditor Rich Text Field
    created = models.DateTimeField(auto_now_add=True) 
    class Meta:
        ordering = ['-created'] 
        #index_together = (('id', 'slug'),)
    def __str__(self):
        return self.title 

    def get_absolute_url(self):
        return reverse('product_detail',
                       args=[self.id, self.slug])

   # def get_absolute_url(self):
        #return reverse('product_detail', kwargs={"pk": self.pk})
        

    objects = models.Manager() 
    active = ActiveProductManager()               
    objects = ActiveManager()

    featured = FeaturedProductManager()

    last_spoken_to = models.ForeignKey(
        User,
        null=True,
        related_name="cs_chats",
        on_delete=models.SET_NULL,
    )  


def cross_sells_hybrid(self):
        from categories.models import Basket, BasketLine
        from django.contrib.auth.models import User
        from django.db.models import Q
        baskets = Basket.objects.filter(basketline__product=self) 
        users = User.objects.filter(basket__basketline__product=self) 
        items = BasketLine.objects.filter( Q(basket__in=baskets) |
                    Q(basket__user__in=users)
                    ).exclude(product=self)
        products = Product.filter(basketline__in=items).distinct() 
        return products



class ProductImage(models.Model): 
    product = models.ForeignKey(Product, on_delete=models.CASCADE )
    image = models.ImageField(upload_to="product-images")
    featured = models.BooleanField(default=False, help_text="1=featured") 
    thumbnail = models.ImageField( upload_to="product-thumbnails", null=True
)



class Address(models.Model): 
    SUPPORTED_COUNTRIES = (
        ("uk", "United Kingdom"),
        ("us", "United States of America"), 
    )
    user = models.ForeignKey(User, on_delete=models.CASCADE) 
    name = models.CharField(max_length=60)
    telephone = models.CharField(max_length=60)
    address1 = models.CharField("Address line 1", max_length=60) 
    address2 = models.CharField(
    "Address line 2", max_length=60, blank=True 
    )
    zip_code = models.CharField(
        "ZIP / Postal code", max_length=12
    )
    city = models.CharField(max_length=60) 
    country = models.CharField(max_length=3, choices=SUPPORTED_COUNTRIES 
    )

    def __str__(self): 
        return ", ".join(
        [
                self.name,
                self.telephone,
                self.address1, 
                self.address2, 
                self.zip_code, 
                self.city, 
                self.country,
        ] 
        )

class Basket(models.Model):
    OPEN = 10
    SUBMITTED = 20
    STATUSES = ((OPEN, "Open"), (SUBMITTED, "Submitted"))
    user = models.ForeignKey(
        User, on_delete=models.CASCADE, blank=True, null=True
    )
    status = models.IntegerField(choices=STATUSES, default=OPEN)

    def is_empty(self):
        return self.basketline_set.all().count() == 0

    def count(self):
        return sum(i.quantity for i in self.basketline_set.all())

    def create_order(self, billing_address, shipping_address):
        if not self.user:
            raise exceptions.BasketException(
                "Cannot create order without user"
            )

        logger.info(
            "Creating order for basket_id=%d"
            ", shipping_address_id=%d, billing_address_id=%d",
            self.id,
            shipping_address.id,
            billing_address.id,
        )

        order_data = {
            "user": self.user,
            "billing_name": billing_address.name,
            "billing_address1": billing_address.address1,
            "billing_address2": billing_address.address2,
            "billing_zip_code": billing_address.zip_code,
            "billing_city": billing_address.city,
            "billing_country": billing_address.country,
            "shipping_name": shipping_address.name,
            "shipping_address1": shipping_address.address1,
            "shipping_address2": shipping_address.address2,

categories/templates/tags/pagination_links.html
{% if product.has_other_pages %} {% if product.has_previous %}
<a href="{{ request.path }}?{{ params }}&page={{ product.previous_page_number }}"> &laquo; Previous
</a> {% else %}&laquo; Previous 
{% endif %}
| Page {{ product.number }} of {{ paginator.num_pages }} | 
{% if product.has_next %}
<a href="{{ request.path }}?{{ params }}&page={{ product.next_page_number }}"> 
    Next &raquo;
</a> {% else %}
Next &raquo; {% endif %}
{% endif %}

categories/templates/tags/product_list.html
<div class="container">
<div id="owl-demo">

{% if forloop.first %}
<h3>{{ header_text }}</h3> 
{% endif %}
{% include 'tags/product_thumbs.html' %} 
{% include 'tags/product_thumbnail.html' %} 
{% if forloop.last %}
<div class="cb">&nbsp;</div> 
{% endif %}

</div>
</div>

categories/templates/tags/product_thumbnail.html
{%load static %}
  <style>
* {
  box-sizing: border-box;
  margin: 0;
  padding: 0;
}

.flex-wrapper {
  display: flex;
  flex-wrap: wrap;
}

.flex-wrapper > div {
  width: 100%;
  max-width: 25%;
  padding: 10px;

}

@media only screen and (max-width: 600px) {
  .flex-wrapper > div {
    max-width: 50%;
  }
}
@media (min-width: 768px) {
      .bd-placeholder-img-lg {
        font-size: 3.5rem;
      }
    }
.bd-placeholder-img {
  font-size: 1.125rem;
  text-anchor: middle;
  -webkit-user-select: none;
  -moz-user-select: none;
  user-select: none;
    }

.img-container {
   position: relative;
   overflow:hidden;
   height: 150px;
}

.img-container img {
  position: absolute;
  top:0;
  left:0;
  width: 100%;
  height:100%;
  object-fit: cover;
}
  </style>
    <!-- Section START -->
        <div class="row">
          <div class="col-md-12">
            <!-- Title -->
            <div class="mb-4 d-md-flex justify-content-between align-items-center">
              <h2 class="m-0"><i class="bi bi-megaphone"></i> </h2>

            </div>
            <div class="tiny-slider arrow-hover arrow-blur arrow-dark arrow-round">
              <div class="tiny-slider-inner"
                data-autoplay="true"
                data-hoverpause="true"
                data-gutter="24"
                data-arrow="true"
                data-dots="false"
                data-items-xl="6"
                data-items-md="4"
                data-items-sm="3.5"
                data-items-xs="2.2">

                <!-- Card item START -->
              
                {% for p in products %}             
                <div class="item">
                  <div class="pad15">
                    <div className="pad15">
                      <a href="{{ p.get_absolute_url }}">
                       <div class="img-container">
                        {% for ima in p.productimage_set.all %}
                        <img src="{{ ima.image.url }}" alt="cover">
                        {% endfor %}
                      </div>
                      <div class="pad15">
                    <h5 class="card-title"><a href="{{ p.get_absolute_url }}"> {{ p.title }}</a> </h5>
                    <ul class="product_price list-unstyled">
                     
                      <li class="new_price">Kes: {{ p.price }}</li>
                  </ul>
                  </div>
                      </a>
                  </div>
                  </div>
              </div>
              {% endfor %}
      </div>
    </div>
  </div>
</div>
</div>
</section>

categories/templates/tags/product_thumbs.html
{% for p in products %}
{% if forloop.first %}
<h3>{{ header_text }}</h3> 
{% endif %}

{% endfor %}

categories/templates/tags/search_box.html
<form action="{% url "search_products" %}" method="GET" action="search">
  <button class="button-search"><i class="fas fa-search"></i></button>
  <input id="q" name="q" value="{{ request.GET.q }}" required="required" 
  class="search-input" type="text" placeholder="Search...">
</form> 

<form id="search" action="{% url "search_products" %}" method="get">
  <h3><label for="id_q">Search</label></h3>
  <div style="text-align:right;"> 
  {{ form.q }}
    <input type="submit" value="Search"/> 
  </div>
</form>